### ISSUE TITLE
Questions on your work

### ISSUE THREAD

**Issue by Michael1337** [BaoLong-Kong/bandsync#1]
Hi there,
I just found your project, which looks pretty cool. I hope you got a good grade for that!
I'm currently working on a similar project and would like to know if you succeeded in connecting and running your project on a mobile device (Android). If so, could you please provide more detailed instructions on how you did that?
If you'd like, you can also write me an email at michael.weber @ stud-mail.uni-wuerzburg.de (English or German :))
Any response is highly appreciated!

**Comment by BaoLong-Kong** [comment]
Hi Michael,
i dont see a reason for it to not work on mobile.
I'll go into more detail in a personal mail, which is easier for me.
